'use strict';
const $=id=>document.getElementById(id),KEY='accessproof-draft-v1';let lang='en',report=null,previous=null;
const copy={en:{private:'HTML stays on this device',headline:'Make access<br><em>part of done.</em>',intro:'Find common accessibility gaps in HTML before you publish. Keep evidence, decide the fix, and check what changed.',scope:'Static source preflight · Human review required',input:'Start with your HTML',source:'Page source',hint:'Parsed in an inert template; your scripts and page resources are not loaded.',broken:'Try a broken page',fixed:'Try the improved page',scan:'Check source ↗',clear:'Clear local work',empty:'A useful check explains itself.',emptyText:'Add source or choose a sample. Every finding includes the element, its impact and a repair pattern.',report:'Your preflight',stale:'Source changed — run again before export',errors:'Potential barriers',reviews:'Review prompts',reviewed:'Reviewed',notice:'These are source checks, not a WCAG pass/fail. CSS, interaction, assistive technology and meaning need additional testing.',filter:'Show findings',all:'All',barriers:'Potential barriers',manual:'Review prompts',unreviewed:'Unreviewed',manualTitle:'Finish with a human check',keyboard:'Use Tab, Shift+Tab, Enter and Escape through the rendered page.',contrast:'Check computed contrast, zoom and focus visibility in the actual layout.',screenReader:'Test names, reading order and announcements with a screen reader.',md:'Export review ↓',json:'Export JSON ↓',import:'Import review',print:'Print / PDF',footer:'Source evidence. Thoughtful repairs.',evidence:'Element evidence',fix:'Suggested pattern — adapt before use',mark:'Reviewed by me',note:'Record your decision or verification evidence',ready:'Preflight ready. Review the findings and record your decisions.',invalid:'Add HTML, up to 100,000 characters.',saved:'Saved locally.',storage:'Local storage unavailable. Export to avoid losing work.',none:'No findings in this filter. Additional manual checks still apply.',clearConfirm:'Clear the source and local review?',discard:'Replace this source and review?'},zh:{private:'HTML 留在本机',headline:'让每个人，<br><em>都能使用。</em>',intro:'发布前检查网页源码里的常见无障碍缺口。保留证据，决定如何修复，再检查改动。',scope:'静态源码预检 · 仍需人工核对',input:'从网页 HTML 开始',source:'网页源码',hint:'在惰性模板中解析，不加载源码中的脚本或页面资源。',broken:'试试有问题的页面',fixed:'试试改进后的页面',scan:'检查源码 ↗',clear:'清除本机记录',empty:'每个检查，都应说得清楚。',emptyText:'粘贴源码或选择样例。问题、原因和修复模式会显示在这里。',report:'预检结果',stale:'源码已变更，请重新检查后导出',errors:'潜在障碍',reviews:'人工复核提示',reviewed:'已复核',notice:'这是源码检查，不代表通过 WCAG。样式、交互、辅助技术和内容含义仍需实际测试。',filter:'筛选问题',all:'全部',barriers:'潜在障碍',manual:'人工提示',unreviewed:'未复核',manualTitle:'最后，实际使用一次',keyboard:'在运行页面用 Tab、Shift+Tab、Enter 和 Escape 检查操作。',contrast:'检查实际样式中的对比度、缩放和焦点可见性。',screenReader:'用屏幕阅读器检查名称、阅读顺序和动态提示。',md:'导出复核文档 ↓',json:'导出 JSON ↓',import:'导入复核记录',print:'打印 / PDF',footer:'保留源码证据，认真修复障碍。',evidence:'元素证据',fix:'修复模式 · 请按实际内容调整',mark:'我已复核',note:'记录修复决定或验证证据',ready:'预检完成。请逐项复核并留下决定。',invalid:'请输入 HTML，最多 100,000 字。',saved:'已保存在本机。',storage:'本机存储不可用，请及时导出。',none:'当前筛选没有问题，仍需实际使用测试。',clearConfirm:'清除源码和本机复核记录？',discard:'替换当前源码和复核记录？'}};
const broken='<!doctype html>\n<html>\n<head><title></title></head>\n<body>\n<h1>Community workshop</h1>\n<img src="workshop.jpg">\n<form>\n<input id="email" placeholder="Email">\n<button><svg aria-hidden="true"></svg></button>\n</form>\n</body></html>';
const fixed='<!doctype html>\n<html lang="en">\n<head><title>Community workshop registration</title></head>\n<body><main>\n<h1>Community workshop</h1>\n<img src="workshop.jpg" alt="Volunteers assembling a raised garden bed">\n<form>\n<label for="email">Email address</label>\n<input id="email" type="email" autocomplete="email">\n<button type="submit">Register for the workshop</button>\n</form>\n</main></body></html>';
const t=k=>copy[lang][k]||k;
Object.assign(copy.en,{resolved:'Findings no longer detected',added:'New findings',retained:'Unchanged evidence',comparisonNote:'Disappearing source findings do not prove the rendered page is accessible.',invalidImport:'Cannot import: use AccessProof JSON up to 1 MB.',imported:'Review imported; findings have been rechecked against source.'});
Object.assign(copy.zh,{resolved:'不再检测到的问题',added:'新增问题',retained:'证据未变的问题',comparisonNote:'源码问题消失不等于实际页面已无障碍。',invalidImport:'导入失败：请使用不超过 1 MB 的 AccessProof JSON。',imported:'记录已导入，已根据源码重新检查问题。'});
function node(tag,cls,value){const n=document.createElement(tag);if(cls)n.className=cls;if(value!==undefined)n.textContent=value;return n;}
function status(key){$('status').textContent=t(key);}
function translate(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';for(const n of document.querySelectorAll('[data-i18n]'))if(n.dataset.i18n==='headline')n.innerHTML=t('headline');else n.textContent=t(n.dataset.i18n);$('language').textContent=lang==='en'?'中文':'English';}
function save(){try{localStorage.setItem(KEY,JSON.stringify({lang,source:$('source').value,report,previous}));}catch{status('storage');}}
function freshness(){const stale=!!report&&report.source!==$('source').value;$('stale').hidden=!stale;for(const id of ['export-md','export-json','print'])$(id).disabled=stale||!report;}
function metrics(){if(!report)return;$('error-count').textContent=report.issues.filter(x=>x.severity==='error').length;$('review-count').textContent=report.issues.filter(x=>x.severity==='review').length;$('done-count').textContent=report.issues.filter(x=>x.reviewed).length+'/'+report.issues.length;}
function render(){ $('empty').hidden=!!report;$('report').hidden=!report;freshness();if(!report)return;metrics();const comparison=$('comparison');comparison.replaceChildren();comparison.hidden=!previous;if(previous){const delta=AccessProof.compare(previous,report);for(const key of ['resolved','added','retained'])comparison.append(node('p','',t(key)+' · '+delta[key].length));comparison.append(node('p','',t('comparisonNote')));}const host=$('findings');host.replaceChildren();const filter=$('filter').value;for(const issue of report.issues){if(filter==='open'&&issue.reviewed||['error','review'].includes(filter)&&issue.severity!==filter)continue;const card=node('article','finding'),head=node('div','finding-head');head.append(node('h3','',issue.title),node('span','tag',issue.rule));card.append(head,node('p','',issue.why),node('strong','tag',t('evidence')+' · '+issue.selector),node('pre','',issue.evidence||issue.selector),node('strong','tag',t('fix')),node('pre','',issue.fix));const label=node('label'),check=node('input');check.type='checkbox';check.checked=!!issue.reviewed;check.setAttribute('aria-label',t('mark')+' · '+issue.title);check.addEventListener('change',()=>{issue.reviewed=check.checked;metrics();save();if($('filter').value==='open')render();});label.append(check,document.createTextNode(t('mark')));const note=node('textarea');note.value=issue.note||'';note.maxLength=3000;note.placeholder=t('note');note.setAttribute('aria-label',issue.title+' '+t('note'));note.addEventListener('input',()=>{issue.note=note.value;issue.reviewed=false;check.checked=false;metrics();save();});card.append(label,note,node('p','print-note',t('note')+' · '+(issue.note||'—')));host.append(card);}if(!host.children.length)host.append(node('p','',t('none')));}
function scan(){try{const next=AccessProof.scan($('source').value,lang);if(report&&report.source!==next.source)previous=JSON.parse(JSON.stringify(report));report=AccessProof.merge(next,report);render();status('ready');save();}catch{status('invalid');}}
function download(kind){if(!report||report.source!==$('source').value)return;const content=kind==='md'?AccessProof.markdown(report):JSON.stringify(report,null,2),url=URL.createObjectURL(new Blob([content],{type:kind==='md'?'text/markdown;charset=utf-8':'application/json;charset=utf-8'})),a=node('a');a.href=url;a.download='accessproof-review.'+kind;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('scan').addEventListener('click',scan);$('source').addEventListener('input',()=>{freshness();save();});$('filter').addEventListener('change',render);$('export-md').addEventListener('click',()=>download('md'));$('export-json').addEventListener('click',()=>download('json'));$('print').addEventListener('click',()=>{const filter=$('filter').value;$('filter').value='all';render();window.addEventListener('afterprint',()=>{$('filter').value=filter;render();},{once:true});window.print();});
$('import-json').addEventListener('click',()=>$('import-file').click());
$('import-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('size');const restored=AccessProof.restore(JSON.parse(await file.text()));if(report?.issues.some(x=>x.reviewed||x.note)&&!confirm(t('discard')))return;report=restored;previous=null;lang=restored.lang==='zh'?'zh':'en';$('source').value=restored.source;translate();render();save();status('imported');}catch{status('invalidImport');}finally{event.target.value='';}});
for(const [id,source] of [['sample-broken',broken],['sample-fixed',fixed]])$(id).addEventListener('click',()=>{if(report?.issues.some(x=>x.reviewed||x.note)&&!confirm(t('discard')))return;$('source').value=source;render();save();});
$('language').addEventListener('click',()=>{lang=lang==='en'?'zh':'en';if(report)report=AccessProof.restore(report,lang);translate();render();save();});
$('clear').addEventListener('click',()=>{if(!confirm(t('clearConfirm')))return;report=null;previous=null;$('source').value='';try{localStorage.removeItem(KEY);}catch{status('storage');}render();});
try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&typeof saved.source==='string'&&saved.source.length<=100000){lang=saved.lang==='zh'?'zh':'en';$('source').value=saved.source;if(saved.report)report=AccessProof.restore(saved.report,lang);if(saved.previous)previous=AccessProof.restore(saved.previous,lang);}}catch{}translate();render();
